import { api, mockDelay, USE_MOCK } from "./axios";
import type { Language } from "@/types/submission";

export interface EnglishToCodeResponse {
  code: string;
  language: Language;
}

const SAMPLE_OUTPUTS: Record<Language, string> = {
  mylang: `// Generated by CodeForge AI\nfn main() {\n  let a = read()\n  let b = read()\n  print(a + b)\n}`,
  python: `# Generated by CodeForge AI\na = int(input())\nb = int(input())\nprint(a + b)`,
  c: `#include <stdio.h>\n\nint main() {\n  int a, b;\n  scanf("%d %d", &a, &b);\n  printf("%d\\n", a + b);\n  return 0;\n}`,
  cpp: `#include <iostream>\nusing namespace std;\n\nint main() {\n  int a, b;\n  cin >> a >> b;\n  cout << a + b << endl;\n  return 0;\n}`,
  java: `import java.util.Scanner;\n\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int a = sc.nextInt();\n    int b = sc.nextInt();\n    System.out.println(a + b);\n  }\n}`,
};

export async function translateEnglishToCode(
  english: string,
  language: Language,
): Promise<EnglishToCodeResponse> {
  if (USE_MOCK) {
    void english;
    return mockDelay({ code: SAMPLE_OUTPUTS[language], language }, 900);
  }
  const { data } = await api.post<{ success: boolean; data: any; message: string }>(
    "/ai/translate",
    { englishContent: english, language },
  );
  const result = data.data;
  return { code: result.code, language: result.language };
}
