/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as EnglishToCodeRouteImport } from './routes/english-to-code'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as ProblemsIdRouteImport } from './routes/problems.$id'
import { Route as LearnTopicRouteImport } from './routes/learn.$topic'
import { Route as ContestsIdRouteImport } from './routes/contests.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishToCodeRoute = EnglishToCodeRouteImport.update({
  id: '/english-to-code',
  path: '/english-to-code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProfileRoute,
} as any)
const ProblemsIdRoute = ProblemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProblemsRoute,
} as any)
const LearnTopicRoute = LearnTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => LearnRoute,
} as any)
const ContestsIdRoute = ContestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contests': typeof ContestsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/english-to-code': typeof EnglishToCodeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/contests/$id': typeof ContestsIdRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contests': typeof ContestsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/english-to-code': typeof EnglishToCodeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/contests/$id': typeof ContestsIdRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contests': typeof ContestsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/english-to-code': typeof EnglishToCodeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRouteWithChildren
  '/problems': typeof ProblemsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/contests/$id': typeof ContestsIdRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contests'
    | '/dashboard'
    | '/english-to-code'
    | '/leaderboard'
    | '/learn'
    | '/problems'
    | '/profile'
    | '/contests/$id'
    | '/learn/$topic'
    | '/problems/$id'
    | '/profile/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contests'
    | '/dashboard'
    | '/english-to-code'
    | '/leaderboard'
    | '/learn'
    | '/problems'
    | '/profile'
    | '/contests/$id'
    | '/learn/$topic'
    | '/problems/$id'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/contests'
    | '/dashboard'
    | '/english-to-code'
    | '/leaderboard'
    | '/learn'
    | '/problems'
    | '/profile'
    | '/contests/$id'
    | '/learn/$topic'
    | '/problems/$id'
    | '/profile/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContestsRoute: typeof ContestsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EnglishToCodeRoute: typeof EnglishToCodeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LearnRoute: typeof LearnRouteWithChildren
  ProblemsRoute: typeof ProblemsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-to-code': {
      id: '/english-to-code'
      path: '/english-to-code'
      fullPath: '/english-to-code'
      preLoaderRoute: typeof EnglishToCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/problems/$id': {
      id: '/problems/$id'
      path: '/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof ProblemsIdRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/learn/$topic': {
      id: '/learn/$topic'
      path: '/$topic'
      fullPath: '/learn/$topic'
      preLoaderRoute: typeof LearnTopicRouteImport
      parentRoute: typeof LearnRoute
    }
    '/contests/$id': {
      id: '/contests/$id'
      path: '/$id'
      fullPath: '/contests/$id'
      preLoaderRoute: typeof ContestsIdRouteImport
      parentRoute: typeof ContestsRoute
    }
  }
}

interface ContestsRouteChildren {
  ContestsIdRoute: typeof ContestsIdRoute
}

const ContestsRouteChildren: ContestsRouteChildren = {
  ContestsIdRoute: ContestsIdRoute,
}

const ContestsRouteWithChildren = ContestsRoute._addFileChildren(
  ContestsRouteChildren,
)

interface LearnRouteChildren {
  LearnTopicRoute: typeof LearnTopicRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnTopicRoute: LearnTopicRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface ProblemsRouteChildren {
  ProblemsIdRoute: typeof ProblemsIdRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsIdRoute: ProblemsIdRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUsernameRoute: ProfileUsernameRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContestsRoute: ContestsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EnglishToCodeRoute: EnglishToCodeRoute,
  LeaderboardRoute: LeaderboardRoute,
  LearnRoute: LearnRouteWithChildren,
  ProblemsRoute: ProblemsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
